# Site settings
title: Henrique Jung - Software developer
description: "Henrique Jung personal webportfolio"
baseurl: "" # for test: remove string '/space-jekyll-template' to ''
url: "https://henriquenj.github.io/" # for test: remove string 'http://victorvoid.github.io' to '' but in production: 'https://yourusername.githu.io'
# User settings
username: Henrique Jung
user_title: Henrique Jung
email: henriquenj@gmail.com
# twitter_username:
github_username:  henriquenj
# gplus_username:  henriquenj
linkedin_public_url: henriquenj # Example: For public profile 'www.linkedin.com/in/john-smith', 'john-smith' is your linkedin_public_url
profile_picture: /assets/img/henrique_profile.jpg

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/


# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
links:
  - title: home
    url: /
  - title: about me
    url: /about
# projects in header index
projects:
  - name: asciilang
    url: https://github.com/victorvoid/asciilang
  - name: vim-frontend
    url: https://github.com/victorvoid/vim-frontend
  - name: generator-capybara
    url: https://github.com/victorvoid/generator-capybara 
# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
